# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubnet', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterestTag',
        ),
    ]
