# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hubnet', '0002_delete_interesttag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('startDate', models.DateTimeField()),
                ('stopDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Midpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagId', models.CharField(max_length=30)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubnet.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubnet.Event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubnet.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorId', models.IntegerField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubnet.Sensor'),
        ),
        migrations.AddField(
            model_name='path',
            name='endSensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_sensor', to='hubnet.Sensor'),
        ),
        migrations.AddField(
            model_name='path',
            name='midpoint1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_midpoint', to='hubnet.Midpoint'),
        ),
        migrations.AddField(
            model_name='path',
            name='midpoint2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_midpoint', to='hubnet.Midpoint'),
        ),
        migrations.AddField(
            model_name='path',
            name='midpoint3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_midpoint', to='hubnet.Midpoint'),
        ),
        migrations.AddField(
            model_name='path',
            name='startSensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_sensor', to='hubnet.Sensor'),
        ),
        migrations.AddField(
            model_name='event',
            name='interestTags',
            field=models.ManyToManyField(to='hubnet.Group'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(to='hubnet.Participant'),
        ),
        migrations.AddField(
            model_name='event',
            name='paths',
            field=models.ManyToManyField(to='hubnet.Path'),
        ),
        migrations.AddField(
            model_name='event',
            name='sensors',
            field=models.ManyToManyField(to='hubnet.Sensor'),
        ),
    ]
