# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubnet', '0005_auto_20161229_0038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
    ]
