# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubnet', '0007_auto_20161230_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='group',
            new_name='groups',
        ),
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
        migrations.AddField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hubnet.Event'),
        ),
        migrations.AlterField(
            model_name='midpoint',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
