# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubnet', '0008_auto_20161230_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
