# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 16:17
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubnet', '0010_auto_20161230_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='paths',
        ),
        migrations.AddField(
            model_name='event',
            name='obstacles',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), null=True, size=None),
        ),
        migrations.AddField(
            model_name='path',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hubnet.Event'),
        ),
    ]
