# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubnet', '0011_auto_20170104_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='midpoint',
        ),
        migrations.AddField(
            model_name='midpoint',
            name='path',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hubnet.Path'),
        ),
    ]
