# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubnet', '0012_auto_20170105_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='color',
            field=models.CharField(max_length=7),
        ),
    ]
