# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubnet', '0015_auto_20170109_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='second_antenna',
            field=models.IntegerField(null=True),
        ),
    ]
