# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubnet', '0016_sensor_second_antenna'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='second_antenna',
            new_name='secondAnt',
        ),
    ]
