# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-28 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubnet', '0017_auto_20170221_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
